### ISSUE TITLE
Gemma-4-31B: CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES on DGX Spark GB10 (SM 12.1) — topk sampling kernel

### ISSUE THREAD

**Issue by CINOAdam** [modular/mojo#6488]
## Environment

* **System**: NVIDIA DGX Spark (AI TOP ATOM variant)
* **CPU**: ARM64 (Grace), 20 cores
* **GPU**: NVIDIA GB10, SM 12.1a
* **Memory**: 128GB unified (shared CPU/GPU)
* **MAX Version**: 26.4.0.dev2026050306 (nightly, May 3 2026)
* **Model**: google/gemma-4-31b-it (local, NVMe)
* **OS**: Ubuntu, kernel 6.x, CUDA 13.0

## Summary

MAX Engine 26.4.0 nightly successfully **compiles and loads** Gemma-4-31B-IT on the DGX Spark GB10, but crashes on the **first inference request** due to a CUDA kernel resource limit violation in the top-K/top-P sampling kernel.

**Greedy sampling (temperature=0) works perfectly.** Only the fused top-K/top-P sampling kernel fails.

## What Works

| Step | Status | Time |
| -- | -- | -- |
| Model detection (Gemma4ForConditionalGeneration) | ✅ | instant |
| Language model graph build | ✅ | 3s |
| Language model kernel compilation (SM 12.1) | ✅ | 285s |
| Vision model compilation | ✅ | 5s |
| Weight loading | ✅ | \~30s |
| Device graph capture (batch 1..4) | ✅ | 36s |
| Server startup (OpenAI API) | ✅ | instant |
| `/v1/models` endpoint | ✅ | works |
| **Greedy sampling (temperature=0)** | ✅ | **works** |
| **Top-K/Top-P sampling (temperature>0)** | ❌ | **crashes** |

## Error

```
ERROR: Worker exception, shutting down: An error occurred in kernel entry point named "region_15":
An error occurred in kernel named "stub_386":
max/kernels/src/nn/topk_fi.mojo:1419:49 failed calling 
'topk_topp_sampling_from_prob_float32_int64_False_ddb3285f' 
on device cuda:0 with error 'CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES 
(too many resources requested for launch)'
```

The fused token sampling kernel requests more resources (registers/shared memory/threads per block) than SM 12.1 supports.

## Workaround

**Greedy sampling works.** Setting `temperature: 0` bypasses the broken kernel entirely:

```bash
curl http://localhost:8091/v1/chat/completions \
  -d '{"model":"...","messages":[{"role":"user","content":"Hello"}],"temperature":0,"max_tokens":100}'
# Returns valid response
```

### 1\. Memory Estimation Bug (unified memory)

`MemoryEstimator.free_memory()` reads CUDA-reported GPU memory (\~34GB) instead of system available memory (\~116GB). Models >34GB are rejected even though the unified memory pool is 128GB.

**Workaround**: Monkey-patch `MemoryEstimator.free_memory` to read `/proc/meminfo` on unified memory systems (DGX Spark, Grace Blackwell).

### 2\. Pydantic Deferred Type Annotations

`PipelineConfig` and `MAXModelConfig` have deferred type annotations referencing `torch.Tensor`. When the CLI creates these configs, torch hasn't been imported, causing `PydanticUserError`.

**Workaround**: Import torch and call `model_rebuild()` on both models before the CLI runs.

### 3\. CUDA Memory Overallocation (OOM)

Without constraints, CUDA allocates the entire unified memory pool during model loading + graph capture, OOMing the system.

**Workaround**: Use a CUDA memory limiter shim (LD_PRELOAD interception of cuMemAlloc) with a 96GB cap to leave headroom for the OS.

### 4\. Missing conda Dependencies

The `max` conda package doesn't declare many required Python dependencies. Had to manually add: tqdm, pydantic, pillow, transformers, safetensors, tokenizers, sentencepiece, accelerate, msgspec, opentelemetry-\*, pyzmq, llguidance, av, prometheus_client, python-json-logger, aiofiles, asgiref, openai, sse-starlette, pytorch.

## Reproduction

```bash
# On DGX Spark with Gemma-4-31B local
pixi init --channel https://conda.modular.com/max-nightly
pixi add max pytorch tqdm pydantic pillow transformers safetensors \
  tokenizers sentencepiece accelerate msgspec opentelemetry-api \
  opentelemetry-sdk opentelemetry-exporter-otlp-proto-http pyzmq \
  llguidance av prometheus_client python-json-logger aiofiles \
  asgiref openai sse-starlette
pixi add --pypi 'opentelemetry-exporter-prometheus==0.62b1'

# Apply workarounds (unified memory + pydantic + CUDA limiter)
# Then:
max serve --model-path /path/to/gemma-4-31b-it --port 8091 --max-batch-size 4

# temperature=0 works:
curl localhost:8091/v1/chat/completions -d '{"model":"...","messages":[{"role":"user","content":"Hello"}],"temperature":0}'
# ✅ Returns "Hello!"

# temperature>0 crashes:
curl localhost:8091/v1/chat/completions -d '{"model":"...","messages":[{"role":"user","content":"Hello"}]}'
# ❌ CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES
```

## Proposed Fix

The `topk_topp_sampling` kernel at `topk_fi.mojo:1419` needs SM 12.1-aware resource tuning:

1. Reduce thread block size for SM 12.x
2. Add `--maxrregcount` equivalent for SM 12.1 builds
3. Or provide a fallback non-fused sampling path

Happy to test any patches on our DGX Spark hardware.

**Related**: modular/modular#5920, modular/modular#6396

**Comment by CINOAdam** [comment]
## Update: Bug confirmed on RTX PRO 6000 Blackwell (CC 12.0)

We've now reproduced this on a second Blackwell GPU:

| GPU | Compute Capability | Same Bug? |
|-----|-------------------|-----------|
| DGX Spark GB10 | SM 12.1a | ✅ CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES |
| **RTX PRO 6000 Blackwell WS** | **SM 12.0** | ✅ **Same error, same kernel** |

**This confirms the bug affects the entire Blackwell architecture family (CC 12.x), not just the DGX Spark.**

Same kernel: `topk_topp_sampling_from_prob_float32_int64_False_ddb3285f` at `topk_fi.mojo:1419`
Same workaround: `temperature: 0` (greedy sampling) works perfectly on both GPUs.

Tested on MAX 26.4.0.dev2026050306 nightly (same version on both).

Additional note: On the RTX PRO 6000 (Vast.ai instance), we also hit a `multiprocessing.freeze_support()` issue when running MAX serve under Python 3.14. Fixed by pinning Python <3.14 and adding `if __name__ == "__main__"` guard. This may be worth noting for the packaging — MAX's pixi.toml pulls Python 3.14 by default which is incompatible with the worker spawning.
